### ISSUE TITLE
[Feature Request] Support InternLM

### ISSUE THREAD

**Issue by vansinhu** [ma2za/telegram-llm-guru#1]
Dear telegram-llm-guru developer,

Greetings! I am vansinhu, a community developer and volunteer at InternLM. Your work has been immensely beneficial to me, and I believe it can be effectively utilized in InternLM as well. Welcome to add Discord https://discord.gg/gF9ezcmtM3 . I hope to get in touch with you.

Best regards,
vansinhu

**Comment by ma2za** [comment]
I like my name but I think I will change it to Mr. Telegram-llm-guru Developer in the future  🤣
