### ISSUE TITLE
Dockerfile directory is wrong

### ISSUE THREAD

**Issue by chienming12** [ma2za/telegram-llm-guru#4]
Under compose.yaml, this section stated that the Dockerfile is located in "/voice_journal" which does not exist in the current version.
`build:
      context: .
      dockerfile: src/telegram_llm_bot/bots/voice_journal/Dockerfile
      container_name: base-chatbot`

The current version's Dockerfile is located at "/base_chatbot" instead

Changes to be made (I'm assuming):
`dockerfile: src/telegram_llm_bot/bots/base_chatbot/Dockerfile`

**Comment by ma2za** [comment]
fixed
